#!/usr/bin/env python3
"""demo.py — a synthetic demo profile in one command (`scholion demo`).

Why. A person opening the project for the first time should not have to start by
loading their own genome. What they need is a working dashboard after one command —
otherwise the funnel breaks off at the first step.

**The rule of the demo: this is a different person.** Not the owner of the project
with altered numbers, but a self-contained fictional case — a different sex, a
different age, a different clinical axis. A picture that coincides with anybody's
real profile counts as a defect: a set of findings is personal data in itself, even
when every figure has been replaced. What has to be checked is not «do the numbers
differ» but «is the story recognisable».

The demo persona: a woman of 33, vegetarian, amateur running. The main line is iron
deficiency without anaemia, B12 deficiency and subclinical hypothyroidism against
autoimmune thyroiditis; separately factor V Leiden against a combined oral
contraceptive. Lipids, carbohydrate metabolism and male endocrinology are
deliberately clean in the demo.

The numbers are chosen so that ALL layers of the engine work, the honesty layer
included: some findings are deliberately doubtful, some panels deliberately
incomplete, some percentiles deliberately marked unreliable. A demo in which
everything is green does not show the product.

    python3 src/tools/make_demo_profile.py
    SCHOLION_PROFILE_DIR=demo/profile python3 -m scholion overview

Generation is deterministic: the same input yields a byte-identical profile, so the
files serve both as a test fixture and as a source of screenshots.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

SEED = 20260815
GENERATED = "2026-08-15"
# The default directory comes from the core: out of the source tree that is <repo>/demo,
# for an installed package it is the user's data directory. What used to stand here was
# parents[2], which outside the repository pointed nowhere.
def _default_out() -> Path:
    from . import core
    return core.repo_dir() / "demo" / "profile"

WARN = "SYNTHETIC. A fictional person; the data are generated by make_demo_profile.py and belong to nobody."


def meta(purpose: str, **extra) -> dict:
    m = {"synthetic": True, "purpose": purpose, "warning": WARN, "generated": GENERATED}
    m.update(extra)
    return m


# ── helpers ────────────────────────────────────────────────────────────────
def months(start: str, end: str) -> list[str]:
    y0, m0 = (int(x) for x in start.split("-"))
    y1, m1 = (int(x) for x in end.split("-"))
    out = []
    while (y0, m0) <= (y1, m1):
        out.append(f"{y0:04d}-{m0:02d}")
        m0 += 1
        if m0 == 13:
            m0, y0 = 1, y0 + 1
    return out


def ramp(vals: list[str], lo: float, hi: float, rnd: random.Random, noise: float, nd: int = 1) -> dict:
    """A smooth transition lo→hi over a list of months with reproducible noise."""
    n = max(len(vals) - 1, 1)
    return {m: round(lo + (hi - lo) * i / n + rnd.uniform(-noise, noise), nd)
            for i, m in enumerate(vals)}


def series(points: list[tuple[str, float]]) -> list[dict]:
    return [{"date": d, "value": v} for d, v in points]


# ── 1. metrics.json ────────────────────────────────────────────────────────
def build_metrics() -> dict:
    return {
        "_meta": meta("Demo: anthropometry and profile of a fictional user."),
        "profile": {"sex": "f", "birth_date": "1993-02-19", "height_cm": 166},
        "metrics": {
            "weight": {"name": "Weight", "unit": "kg", "direction": "higher_worse",
                       "series": series([("2023-04", 62.4), ("2024-03", 61.1), ("2025-05", 60.2),
                                         ("2025-11", 59.6), ("2026-06", 59.9)])},
            "bmi": {"name": "BMI", "unit": "kg/m²", "direction": "higher_worse", "ref_high": 25.0,
                    "series": series([("2023-04", 22.6), ("2025-05", 21.8), ("2026-06", 21.7)])},
            "resting_pulse_home": {"name": "Resting pulse (at home)", "unit": "bpm",
                                   "direction": "higher_worse",
                                   "series": series([("2025-05", 58), ("2026-06", 61)]),
                                   "note": "Demo: measured by hand, the method is not standardised."},
        },
    }


# ── 2. labs.json ───────────────────────────────────────────────────────────
def build_labs() -> dict:
    M = {}

    def add(key, name, unit, pts, **kw):
        M[key] = {"name": name, "unit": unit, "series": series(pts), **kw}

    # The main line of the demo: iron deficiency without anaemia — haemoglobin still normal.
    add("ferritin", "Ferritin", "ng/mL",
        [("2023-04", 34), ("2024-03", 26), ("2025-05", 19), ("2025-11", 15), ("2026-06", 13)],
        ref_low=20, ref_high=150, direction="lower_worse",
        note="Demo: the iron store has been falling for the fourth year running while haemoglobin is still normal — there is no anaemia, but there is a deficiency.")
    add("hemoglobin", "Haemoglobin", "g/L",
        [("2023-04", 134), ("2025-05", 129), ("2026-06", 126)], ref_low=120, ref_high=150,
        direction="lower_worse")
    add("iron", "Serum iron", "µmol/L", [("2026-06", 8.9)], ref_low=9.0, ref_high=30.4,
        direction="lower_worse")
    add("tibc", "TIBC", "µmol/L", [("2026-06", 79.4)],
        note="Demo: the lab form prints no reference range, so no flag is raised. A missing range is not the same thing as a normal result.")
    add("transferrin_sat", "Transferrin saturation", "%", [("2026-06", 11.2)],
        ref_low=20, ref_high=50, direction="lower_worse")

    # Vitamin B12 on a vegetarian diet and its trace in the red blood cell.
    add("b12", "Vitamin B12", "pg/mL",
        [("2024-03", 260), ("2025-11", 208), ("2026-06", 176)], ref_low=197, ref_high=1500,
        direction="lower_worse",
        note="Demo: the reference range is very wide (197–1500), so «inside the range» says little — what matters here is the fall from 260 and the crossing of the lower bound.")
    add("mcv", "MCV", "fL",
        [("2023-04", 85.6), ("2024-03", 86.9), ("2025-11", 92.1), ("2026-06", 99.2)],
        ref_low=80, ref_high=100, direction="higher_worse",
        note="Demo: macrocytosis has not set in yet, but the direction matches the fall of B12.")
    add("folate", "Folate", "ng/mL", [("2026-06", 6.8)], ref_low=3.1, ref_high=20.5)
    add("homocysteine", "Homocysteine", "µmol/L", [("2026-06", 13.4)], ref_high=10.0,
        direction="higher_worse")

    # The thyroid: above the range, but the guideline treatment threshold is not reached yet.
    add("tsh", "TSH", "µIU/mL",
        [("2023-04", 2.60), ("2024-03", 3.90), ("2025-11", 5.60), ("2026-06", 6.42)],
        ref_low=0.27, ref_high=4.20, direction="higher_worse",
        note="Demo: above the range, but the threshold from which hypothyroidism is treated regardless of symptoms is 10. A reference range and a threshold for action are different things.")
    add("t4_free", "Free T4", "pmol/L", [("2025-11", 13.4), ("2026-06", 13.1)],
        ref_low=12.0, ref_high=22.0)
    add("anti_tpo", "Anti-TPO antibodies", "IU/mL", [("2026-06", 214)], ref_high=34,
        direction="higher_worse",
        note="Demo: explains where the hypothyroidism comes from, but on its own it calls for no treatment.")

    # Vitamin D: a sufficiency threshold from below.
    add("vitamin_d", "Vitamin D (25-OH)", "ng/mL",
        [("2023-04", 19.0), ("2025-11", 21.4), ("2026-06", 23.8)], ref_low=30, ref_high=100,
        direction="lower_worse")

    # Deliberately clean lines: lipids and carbohydrate metabolism with no findings.
    add("ldl", "LDL cholesterol", "mmol/L", [("2025-11", 2.36), ("2026-06", 2.28)], ref_high=3.34,
        direction="higher_worse")
    add("hdl", "HDL cholesterol", "mmol/L", [("2026-06", 1.78)], ref_low=1.20, direction="lower_worse")
    add("triglycerides", "Triglycerides", "mmol/L", [("2026-06", 0.84)], ref_high=1.70,
        direction="higher_worse")
    add("glucose", "Glucose", "mmol/L", [("2025-11", 4.8), ("2026-06", 4.9)],
        ref_low=4.1, ref_high=6.05)
    add("hba1c", "Glycated haemoglobin", "%", [("2026-06", 5.1)], ref_high=6.0)

    # Blood count and biochemistry: the PhenoAge set, deliberately incomplete in 2025-11.
    add("albumin", "Albumin", "g/L", [("2026-06", 43)], ref_low=35, ref_high=52,
        note="Demo: the 2025-11 panel has no albumin and no alkaline phosphatase — biological age is not computed for it. That is not a hole in the demo but the rule being shown.")
    add("alp", "Alkaline phosphatase", "U/L", [("2026-06", 58)], ref_low=40, ref_high=130)
    add("creatinine", "Creatinine", "µmol/L", [("2025-11", 61), ("2026-06", 59)],
        ref_low=53, ref_high=97)
    add("crp_hs", "High-sensitivity CRP", "mg/L", [("2025-11", 0.8), ("2026-06", 0.9)],
        ref_high=3.0, direction="higher_worse")
    add("lymph_pct", "Lymphocytes, %", "%", [("2025-11", 33), ("2026-06", 31)], ref_low=19, ref_high=37)
    add("rdw", "RDW", "%", [("2025-11", 13.4), ("2026-06", 14.2)], ref_low=11.5, ref_high=14.5,
        direction="higher_worse")
    add("wbc", "White blood cells", "10⁹/L", [("2025-11", 5.4), ("2026-06", 5.1)], ref_low=4.0, ref_high=9.0)
    add("alt", "ALT", "U/L", [("2026-06", 19)], ref_high=33)
    add("esr", "ESR", "mm/h", [("2026-06", 9)], ref_high=20)

    return {"_meta": meta("Demo: laboratory series of a fictional user, five panels 2023–2026.",
                          panels=["2023-04", "2024-03", "2025-05", "2025-11", "2026-06"],
                          honest_gaps="The 2025-11 panel deliberately has no albumin and no alkaline phosphatase — it shows the refusal to compute biological age on an incomplete panel."),
            "markers": M}


# ── 3. medications.json ────────────────────────────────────────────────────
def build_medications() -> dict:
    return {
        "_meta": meta("Demo: the scheme of a fictional user. Not a prescription and not a recommendation.",
                      scheme_date="2026-05-20",
                      note="A couple of positions are chosen so that the interaction layer fires, and one so that the monitoring-tests layer fires."),
        "medications": [
            {"name": "Levothyroxine", "dose": "50 µg", "type": "drug", "status": "active_new",
             "start_date": "2026-05-20",
             "note": "Demo: started at TSH 6.42 with positive anti-TPO antibodies.",
             "monitoring": ["TSH in 6–8 weeks", "free T4"]},
            {"name": "Omeprazole", "dose": "20 mg", "type": "drug", "status": "active",
             "start_date": "2026-02-01",
             "note": "Demo: prescribed by a gastroenterologist; taken in the morning — the same time as the levothyroxine."},
            {"name": "Ferrous sulfate", "dose": "80 mg", "type": "drug", "status": "active_new",
             "scheme": "every other day, on an empty stomach", "start_date": "2026-06-10",
             "note": "Demo: every other day gives better absorption than every day.",
             "monitoring": ["ferritin in 3 months", "haemoglobin"]},
            {"name": "Cyanocobalamin (B12)", "dose": "1000 µg", "type": "supplement",
             "status": "active", "start_date": "2026-06-10"},
            {"name": "Vitamin D3", "dose": "2000 IU", "type": "supplement", "status": "active",
             "start_date": "2025-12-01", "monitoring": ["vitamin D in 3 months"]},
            {"name": "Combined oral contraceptive", "dose": "—", "type": "drug",
             "status": "active", "start_date": "2024-09-01",
             "note": "Demo: taken for the fourth year. To be read together with the clotting genetics."},
            {"name": "Ascorbic acid", "dose": "500 mg", "type": "supplement",
             "status": "active_self", "start_date": "2026-06-10",
             "note": "Demo: taken on the person's own initiative, together with the iron."},
        ],
        "prescription_history": [],
        "planned_labs": ["ferritin and haemoglobin 3 months after the iron was started",
                         "TSH 6–8 weeks after the levothyroxine was started",
                         "albumin and ALP at the next draw — without them the biological age series does not build"],
    }


# ── 4. pharmacogenomics.json ───────────────────────────────────────────────
def build_pgx() -> dict:
    g = [
        ("CYP2D6", "rs3892097", "A/A", "Two non-functional *4 copies — a poor metaboliser: codeine and tramadol are not converted into the active form."),
        ("CYP2C19", "rs12248560", "T/T", "A *17 homozygote — a rapid metaboliser: proton pump inhibitors work more weakly than expected."),
        ("F5", "rs6025", "G/A", "Factor V Leiden, heterozygous — an increased risk of venous thrombosis."),
        ("F2", "rs1799963", "G/G", "Prothrombin G20210A absent."),
        ("TPMT", "rs1142345", "T/T", "Normal enzyme activity."),
        ("NUDT15", "rs116855232", "C/C", "Normal activity."),
        ("VKORC1", "rs9923231", "G/G", "Ordinary sensitivity to warfarin."),
        ("MTHFR", "rs1801133", "T/T", "A homozygote; read together with homocysteine — 13.4 here against a limit of 10."),
        ("FUT2", "rs601338", "A/A", "A non-secretor — affects the composition of the microbiota and the uptake of B12."),
    ]
    return {
        "meta": meta("Demo: the pharmacogenetic genotypes of a fictional user.",
                     subject_id="DEMO-0001",
                     source="Synthetic. In a real profile the genotypes are called from BAM/VCF rather than entered by hand."),
        "genotypes": [{"gene": a, "rsid": b, "genotype": c, "interpretation": d, "source": "demo"}
                      for a, b, c, d in g],
        "star_alleles": {
            "CYP2D6": {"diplotype": "*4/*4", "phenotype": "Poor Metabolizer", "source": "demo"},
            "CYP2C19": {"diplotype": "*17/*17", "phenotype": "Rapid Metabolizer", "source": "demo"},
            "TPMT": {"diplotype": "*1/*1", "phenotype": "Normal Metabolizer", "source": "demo"},
        },
        "warfarin_summary": "Demo: VKORC1 G/G with no CYP2C9 variants — the expected dose is the usual one; the calculation is the doctor's.",
        "current_scheme_check": {
            "checked": GENERATED,
            "verdict": "There are no genetic contraindications to the current demo scheme.",
            "flags": ["A drug matter, not a genetic one: levothyroxine and omeprazole are taken at the same time — the absorption of the hormone drops. Space the doses apart.",
                      "To discuss with a doctor: heterozygous factor V Leiden against a combined oral contraceptive — a combination the doctor has to know about."],
        },
        "future_flags": [
            {"drug": "codeine, tramadol", "why": "CYP2D6 poor metaboliser — there will be no pain relief, a drug of another pathway is needed."},
            {"drug": "clopidogrel", "why": "CYP2C19 *17/*17 — activation is enhanced; a separate conversation when it is prescribed."},
        ],
        "hla": {"B*57:01": "absent", "B*15:02": "absent", "A*31:01": "absent",
                "B*58:01": "absent",
                "note": "Demo: the four drug hypersensitivity alleles are absent."},
    }


# ── 5. prs_results.json ────────────────────────────────────────────────────
def build_prs() -> dict:
    T = [
        ("Venous thromboembolism", "clotting", 94, 0.95, "PGS000803", True, "clinical",
         "A positive control: the high score agrees with the known carriage of factor V Leiden."),
        ("Autoimmune thyroiditis", "immunity", 89, 0.93, "PGS001901", True, "supportive",
         "Coincides with the positive anti-TPO antibodies — the phenotype confirms the score, not the other way round."),
        ("Migraine", "neurology", 81, 0.90, "PGS000330", True, "supportive", None),
        ("Osteoporosis", "bone", 74, 0.92, "PGS000015", True, "supportive", None),
        ("Iron deficiency anaemia", "blood", 67, 0.87, "PGS002102", True, "research", None),
        ("Type 2 diabetes", "metabolism", 22, 0.94, "PGS000804", True, "clinical", None),
        ("Coronary artery disease", "heart", 31, 0.95, "PGS000018", True, "clinical", None),
        ("Body mass index", "metabolism", 38, 0.96, "PGS000841", True, "supportive", None),
        ("Hypothyroidism", "endocrinology", 77, 0.91, "PGS001902", True, "supportive", None),
        ("Breast cancer", "oncology", 88, 0.58, "PGS000004", False, "research",
         "Withdrawn from trust: the model's coverage is 58 % — nearly half of the variants are not called, a percentile is not computed on such an input."),
        ("Irritable bowel syndrome", "gastrointestinal", 92, 0.89, "PGS002091", False, "research",
         "Withdrawn from trust: the model has a near-zero effect size, the percentile is uninformative."),
        ("Ferritin level", "blood", 12, 0.76, "PGS002080", False, "research",
         "Withdrawn from trust: models of the ferritin level do not reproduce between cohorts, and the actual ferritin is measured directly — 13 ng/mL."),
    ]
    traits = []
    # Which of the three deliberately-unreliable traits was withdrawn for WHICH
    # reason. `limits` chooses the remedy from this, not from the wording of the
    # note: a note is prose, and a decision taken from prose is a decision nobody
    # can check. Absent for a trait the PGS layer wrote itself, and then the cause
    # is inferred from the coverage.
    BECAUSE = {"Breast cancer": ["coverage"],
               "Irritable bowel syndrome": ["model"],
               "Ferritin level": ["coverage", "model"]}
    for label, cat, pct, cov, pgs, ok, level, note in T:
        rec = {
            "label": label, "category": cat, "term": label.lower(),
            "percentile": float(pct), "quality_label": "reliable" if ok else "do not trust",
            "match_rate": round(cov, 2), "weight_mass_coverage": round(cov - 0.03, 2),
            "percentile_reliable": ok, "effect_size": level, "pgs_id": pgs,
            "reliable": ok, "source": "demo", "validity_note": note,
        }
        if label in BECAUSE:
            rec["withdrawn_because"] = BECAUSE[label]
        traits.append(rec)
    return {
        "_meta": meta("Demo: the polygenic scores of a fictional user.",
                      subject_id="DEMO-0001", superpopulation="EUR",
                      reliable_count=sum(1 for t in traits if t["reliable"]), total=len(traits),
                      disclaimer="A percentile depends on the model and on the reference population. It is neither a diagnosis nor a probability.",
                      note="Three traits are deliberately marked unreliable — the honesty layer is visible without explanations."),
        "traits": traits,
    }


# ── 6. longevity_findings.json ─────────────────────────────────────────────
def build_longevity() -> dict:
    known = [
        ("rs4880", "SOD2", "Mitochondrial antioxidant defence", "A/G", 1, None, "neutral",
         "The direction depends on selenium status — navigation, not a conclusion.", ["9600096"]),
        ("rs1042522", "TP53", "Cell cycle control", "C/G", 1, True, "🟢 partly favourable",
         "One favourable copy out of two.", ["21376230"]),
        ("rs9536314", "KL", "Klotho, kidney and vascular function", "T/T", 0, None, "neutral",
         "The commonest genotype in the population.", ["12237272"]),
        ("rs1800795", "IL6", "Inflammation", "C/C", 2, True, "🟢 favourable",
         "Agrees with hs-CRP 0.9 mg/L — the phenotype confirms the direction.", ["9686424"]),
        ("rs2802292", "FOXO3", "Insulin pathway", "G/G", 0, False, "⚠️ a practical flag",
         "The favourable allele is absent — that is not a risk but the lack of a bonus.", ["17595297"]),
    ]
    return {
        "_meta": meta("Demo: the longevity layer of a fictional user.",
                      sources={"genotypes": "demo", "catalog": "LongevityMap (HAGR, CC BY 3.0)",
                               "directions": "knowledge/longevity_directions.json"},
                      genotyped=len(known), carriers=3, significant_records=0, significant_carriers=0,
                      known_curated=len(known),
                      unresolved_note="Only the curated core is left in the demo: showing carriage without a resolved direction would be dishonest."),
        "apoe": {"epsilon": "ε3/ε4", "genotype": "ε3/ε4", "rs429358": "T/C", "rs7412": "C/C",
                 "note": "Demo: one copy of ε4. That is a factor, not a diagnosis; the conversation about it belongs with a doctor rather than with a calculator."},
        "known": [{"rsid": r, "gene": g, "label": l, "confidence": "curated", "pmids": p,
                   "action": "no discussion with a doctor required" if fav is not False else "read together with the phenotype",
                   "genotype": gt, "dp": "demo", "copies_favorable": cp, "favorable": fav,
                   "verdict": v, "note": f"{v} · {note}", "status": "resolved"}
                  for r, g, l, gt, cp, fav, v, note, p in known],
        "significant_by_gene": {},
    }


# ── 7. wearable_trends.json ────────────────────────────────────────────────
def build_wearable(rnd: random.Random) -> dict:
    ms = months("2023-01", "2026-06")
    metrics = {
        "Weight": ramp(ms, 62.4, 59.9, rnd, 0.4),
        "BMI": ramp(ms, 22.6, 21.7, rnd, 0.12, 2),
        "BodyFat": ramp(ms, 27.4, 24.1, rnd, 0.35),
        "MuscleMass": ramp(ms, 24.2, 25.1, rnd, 0.2),
        "BodyWater": ramp(ms, 52.0, 54.2, rnd, 0.35),
        "RestingHeartRate": ramp(ms, 54, 61, rnd, 1.0, 0),
        "HRV": ramp(ms, 62, 48, rnd, 2.5, 0),
        "Stress": ramp(ms, 42, 31, rnd, 2.0, 0),
        "BodyBatteryHigh": ramp(ms, 62, 79, rnd, 3.0, 0),
        "BodyBatteryLow": ramp(ms, 18, 26, rnd, 2.0, 0),
        "Respiration": ramp(ms, 15.4, 14.1, rnd, 0.3),
        "VO2Max": ramp(ms, 46, 43, rnd, 0.7, 0),
        "StepsDaily": ramp(ms, 9800, 10400, rnd, 380, 0),
        "IntensityMinutesDaily": ramp(ms, 44, 41, rnd, 4, 0),
        "SleepHours": ramp(ms, 7.4, 7.5, rnd, 0.2, 1),
        "DeepSleepMin": ramp(ms, 68, 64, rnd, 5, 0),
        "RemSleepMin": ramp(ms, 74, 92, rnd, 6, 0),
        "SleepScore": ramp(ms, 68, 79, rnd, 3, 0),
        "SleepStress": ramp(ms, 29, 22, rnd, 2, 0),
        "Bedtime": ramp(ms, 190, 205, rnd, 9, 0),
        "CaloriesDaily": ramp(ms, 2140, 2185, rnd, 55, 0),
    }
    return {
        "_meta": meta("Demo: monthly trends from a wearable and a smart scale.",
                      source="synthetic (the structure repeats a Garmin export)",
                      primary=True, granularity="monthly", range=f"{ms[0]}…{ms[-1]}",
                      units={"RestingHeartRate": "bpm", "HRV": "ms", "Stress": "0–100",
                             "BodyBattery": "0–100", "Respiration": "breaths/min", "VO2Max": "mL/kg/min",
                             "SleepHours": "h", "DeepSleepMin": "min", "RemSleepMin": "min",
                             "Bedtime": "min from 20:00", "Weight": "kg", "BodyFat": "%",
                             "MuscleMass": "kg", "StepsDaily": "steps"}),
        "metrics": metrics,
    }


# ── 8. sleep_nightly.json ──────────────────────────────────────────────────
def build_sleep(rnd: random.Random, nights: int = 420) -> dict:
    out = []
    y, m, d = 2025, 5, 1
    for i in range(nights):
        weekday = (i + 6) % 7          # 5,6 — the weekend, determined by the index
        weekend = weekday >= 5
        late = rnd.gauss(215 if weekend else 196, 26)
        deep = rnd.gauss(66 - (late - 196) * 0.05 + (3 if not weekend else -2), 10)
        deep = max(8.0, min(105.0, deep))
        total = max(300.0, min(580.0, rnd.gauss(444 if not weekend else 478, 44)))
        rem = max(20.0, min(150.0, rnd.gauss(88, 20)))
        light = max(60.0, total - deep - rem - 24)
        out.append({
            "date": f"{y:04d}-{m:02d}-{d:02d}",
            "deep_min": round(deep, 1), "light_min": round(light, 1), "rem_min": round(rem, 1),
            "awake_min": round(max(4.0, rnd.gauss(22, 8)), 1), "total_min": round(total, 1),
            "bedtime_min_from_20": int(max(120, min(430, late))),
            "sleep_stress": int(max(8, min(60, rnd.gauss(23, 7)))),
            "score": int(max(35, min(95, rnd.gauss(76 + (deep - 52) * 0.25, 8)))),
            "awake_count": int(max(0, round(rnd.gauss(2.1, 1.1)))),
            "restless": round(max(0.0, rnd.gauss(9, 3)), 1),
            "respiration": round(rnd.gauss(14.3, 0.5), 1),
            "naps": 0, "confirm": True,
        })
        d += 1
        if d > [31, 29 if y % 4 == 0 else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][m - 1]:
            d, m = 1, m + 1
            if m == 13:
                m, y = 1, y + 1
    return {
        "_meta": meta("Demo: sleep stages night by night. Monthly averages are useless for n-of-1, so the series is nightly.",
                      source="synthetic (the structure repeats a Garmin export)", granularity="nightly",
                      nights=len(out), range=f"{out[0]['date']}…{out[-1]['date']}"),
        "nights": out,
    }


# ── 9. focus.json ──────────────────────────────────────────────────────────
def build_focus() -> dict:
    return {
        "_meta": meta("Demo: the focus of attention — the single task the user is concentrating on."),
        "focus": {
            "id": "ferritin", "title": "Raise ferritin to 50", "started": "2026-06-10",
            "review_every_days": 90,
            "why": "Ferritin has been falling for the fourth year and has reached 13 against a lower bound of 20. Haemoglobin is still normal, so the question is settled now rather than when anaemia appears.",
            "metric": {"kind": "lab", "key": "ferritin", "label": "Ferritin", "unit": "ng/mL",
                       "dir": "higher_better", "baseline": 13.0,
                       "baseline_note": "The last measurement before the drug was started.",
                       "target": 50, "target_source": "a landmark for refilling the store, not the lower bound of the reference range",
                       "target_note": "The lower bound of 20 closes the deficiency formally, but it does not refill the store."},
            "levers": [
                {"id": "alt-day", "title": "Iron every other day rather than daily", "status": "working",
                 "expected": "higher total absorption at a lower dose",
                 "evidence": "hepcidin rises after a dose and blocks absorption on the following day",
                 "check": None},
                {"id": "vit-c", "title": "Take it with ascorbic acid", "status": "working",
                 "expected": "higher absorption", "evidence": "ferric iron is reduced to the ferrous form",
                 "check": None},
                {"id": "tea-gap", "title": "Keep two hours away from tea and coffee",
                 "status": "under test", "expected": "unknown",
                 "evidence": "tannins bind iron in the gut lumen", "check": None},
                {"id": "more-meat", "title": "Add red meat", "status": "not applicable",
                 "expected": "—", "evidence": "the user is a vegetarian — the lever does not apply, kept as rejected",
                 "check": None},
            ],
            "journal": {"why": "A dose is marked on the day it is taken, not reconstructed from memory.",
                        "target_episodes": 30,
                        "fields": [{"id": "date", "label": "Date", "kind": "date", "required": True},
                                   {"id": "taken", "label": "Taken", "kind": "bool", "required": True},
                                   {"id": "with_vitc", "label": "With vitamin C", "kind": "bool", "required": False},
                                   {"id": "note", "label": "Note", "kind": "text", "required": False}]},
            "questions": [
                {"to": "the doctor", "text": "Should the source of the iron loss be looked for when the store falls like this?"},
                {"to": "myself", "text": "On how many of the thirty days did the dose actually happen?"},
            ],
            "done": [],
        },
        "tracks": [
            {"id": "ferritin", "title": "Ferritin", "owner": "the user",
             "why": "The levers are in the user's hands.", "metric": "lab:ferritin", "state": "in progress",
             "closed_today": ["the «add red meat» lever is rejected — it does not fit the way of life"],
             "next": ["ferritin check in 3 months", "keep marking the doses", "keep two hours away from tea"]},
            {"id": "thyroid", "title": "Thyroid", "owner": "the doctor",
             "why": "TSH 6.42 with positive antibodies — the dose is chosen by the doctor.",
             "metric": "lab:tsh", "state": "awaiting a check",
             "closed_today": ["the action threshold of 10 is not crossed — the decision to treat was made on symptoms, not on the figure"],
             "next": ["TSH in 6–8 weeks", "space the levothyroxine and the omeprazole apart in time"]},
        ],
    }


# ── 10. studies.json ───────────────────────────────────────────────────────
def build_studies() -> dict:
    S = [
        ("us-thyroid-2026-05", "2026-05-12", "Thyroid ultrasound",
         "Volume 11.4 cm³, echogenicity unevenly reduced, no nodules found.",
         ["whether there are nodules", "the structure of the gland"],
         ["the function of the gland — that is TSH and free T4", "whether treatment is needed"]),
        ("egd-2026-02", "2026-02-03", "Upper endoscopy",
         "The picture of a superficial gastritis. The H. pylori test is negative. No signs of bleeding found.",
         ["a source of blood loss in the upper tract", "H. pylori"],
         ["a source of blood loss in the lower tract", "coeliac disease — that is serology and a biopsy"]),
        ("ecg-2026-05", "2026-05-12", "Resting ECG",
         "Sinus rhythm 64 per minute, the electrical axis is not deviated, no changes found.",
         ["the rhythm at the moment of the recording"],
         ["episodes outside the recording", "the structure of the heart — that is echocardiography"]),
    ]
    return {
        "_meta": meta("Demo: instrumental studies and doctors' conclusions.",
                      why="A conclusion is data too. As long as it lies in a PDF as prose, the engine does not see it.",
                      glossary="The «answers» and «does not answer» fields are obligatory: a study closes a question, not a diagnosis."),
        "studies": [{"id": i, "date": d, "kind": k, "source": "demo", "conclusion": c,
                     "values": {}, "answers": a, "does_not_answer": n, "open": [], "records": []}
                    for i, d, k, c, a, n in S],
    }


# ── 11. health_goals.json ──────────────────────────────────────────────────
def build_goals() -> dict:
    return {
        "_meta": meta("Demo: the goal for the metrics. The current values are taken live from labs.json and wearable_trends.json.",
                      updated=GENERATED),
        "title": "The goal — refill the iron store and hold the running form",
        "headline": "The running form has held for the third year, but the iron store is draining meanwhile. The goal is to close the deficiency without losing the training volume.",
        "peaks": [{"title": "The best point for endurance", "year": "2025",
                   "text": "VO2max 46 at a resting pulse of 54 — reached before ferritin went below 20."}],
        "targets": [
            {"label": "Ferritin", "source": "lab:ferritin", "best": "34 (2023)", "target": "≥50"},
            {"label": "Vitamin B12", "source": "lab:b12", "best": "260 (2024)", "target": "≥400"},
            {"label": "TSH", "source": "lab:tsh", "best": "2.60 (2023)", "target": "≤2.5"},
            {"label": "VO2max", "source": "wear:VO2Max", "best": "46", "target": "≥46"},
        ],
        "charts": {
            "weight": {"title": "VO2max, mL/kg/min", "cap": "the target line", "source": "wear:VO2Max",
                       "targets": [{"value": 46, "label": "target 46", "color": "#ffd166"}],
                       "min": 36, "max": 52},
            "minis": [
                {"id": "fer", "source": "lab:ferritin", "title": "Ferritin", "cap": "target ≥50",
                 "color": "#ff9a6b", "tgt": 50, "tlabel": "50", "min": 0, "max": 80},
                {"id": "tsh", "source": "lab:tsh", "title": "TSH", "cap": "target ≤2.5",
                 "color": "#7ec8e3", "tgt": 2.5, "tlabel": "2.5", "min": 0, "max": 8},
            ],
        },
    }


# ── 12. lifestyle_brief.json ───────────────────────────────────────────────
def build_brief() -> dict:
    return {
        "_meta": meta("Demo: the lifestyle brief. The wordings are curated, the numbers are substituted by the engine through tokens.",
                      usage="Tokens of the form {wear:VO2Max} are replaced by the live value at the moment of display.",
                      updating="Only the text is edited, the numbers are never typed in by hand.",
                      privacy="There is nothing personal in this file — only wordings."),
        "title": "Lifestyle — a brief", "subtitle": "A demonstration profile",
        "compiled": GENERATED,
        "disclaimer": "Neither a diagnosis nor a prescription. Material for a conversation with a doctor.",
        "snapshot": [
            {"label": "VO2max", "token": "wear:VO2Max", "unit": "mL/kg/min", "min": 34, "max": 52,
             "target_value": 46, "dir": "higher_better", "source": "wearable", "note": ""},
            {"label": "Resting pulse", "token": "wear:RestingHeartRate", "unit": "bpm", "min": 45,
             "max": 75, "target_value": 54, "dir": "lower_better", "source": "wearable",
             "note": "A rising resting pulse while ferritin falls is not a coincidence."},
            {"label": "Weekly volume", "token": "wear:IntensityMinutesDaily", "unit": "min/day",
             "min": 10, "max": 70, "target_value": 45, "dir": "higher_better", "source": "wearable",
             "note": ""},
            {"label": "Steps", "token": "wear:StepsDaily", "unit": "per day", "min": 4000, "max": 14000,
             "target_value": 10000, "dir": "higher_better", "source": "wearable", "note": ""},
            {"label": "Sleep", "token": "wear:SleepHours", "unit": "h", "min": 5, "max": 9,
             "target_value": 7.5, "dir": "higher_better", "source": "wearable", "note": ""},
            {"label": "HRV", "token": "wear:HRV", "unit": "ms", "min": 20, "max": 90,
             "target_value": 60, "dir": "higher_better", "source": "wearable", "note": ""},
        ],
        "sections": [
            {"id": "movement", "title": "Movement",
             "lead": "Four runs a week, the volume steady for the third year. The problem is not the load but the fact that the iron store does not recover under it."},
            {"id": "food", "title": "Food",
             "lead": "Vegetarian for the fifth year, with no B12 monitoring until 2024. Non-haem iron is absorbed worse, and tea straight after a meal does not help that."},
            {"id": "sleep", "title": "Sleep",
             "lead": "Seven and a half hours on average, a steady schedule. There is no separate task for sleep — this is the case where the layer is looked at and left alone."},
        ],
        "actions": [
            "Iron every other day on an empty stomach with vitamin C — that is absorbed better than daily.",
            "Space the levothyroxine and the omeprazole apart in the time of dosing.",
            "Albumin and alkaline phosphatase at the next draw — without them the biological age series does not build.",
        ],
        "dropped": ["«add red meat» — the lever does not apply to a vegetarian, kept as rejected"],
        "blocks": [],
    }


# ── 13. experiments.json ───────────────────────────────────────────────────
def build_experiments() -> dict:
    sched = []
    start = ["2026-03-02", "2026-03-12", "2026-03-22", "2026-04-01", "2026-04-11", "2026-04-21"]
    end = ["2026-03-11", "2026-03-21", "2026-03-31", "2026-04-10", "2026-04-20", "2026-04-30"]
    for i, (s, e) in enumerate(zip(start, end), 1):
        sched.append({"n": i, "label": "A" if i % 2 else "B", "start": s, "end": e})
    return {
        "_meta": meta("Demo: an n-of-1 experiment. The protocol is not edited after the start.",
                      rule="Significance is limited by the number of BLOCKS, not by the number of days. A day without a mark counts as unknown."),
        "experiments": [{
            "id": "evening-walk-hrv",
            "registered": "2026-02-25", "status": "completed",
            "hypothesis": "A thirty-minute walk after dinner raises the night-time HRV.",
            "primary_metric": "wear:HRV", "direction": "higher_better",
            "secondary_metrics": ["sleep.score", "sleep.deep_min"],
            "phase_days": 10, "blocks": 6, "washout_days": 2, "alpha": 0.05,
            "randomization_seed": 7331, "schedule": sched,
            "min_achievable_p": 0.031,
            "feasible": True,
            "compliance_log": {},
            "result": {"effect": "+2.4 ms HRV", "p_block_permutation": 0.156,
                       "p_naive_daily": 0.008,
                       "verdict": "not significant at the level of blocks",
                       "note": "The naive daily p is shown alongside on purpose: it is twenty times smaller and is entirely a consequence of the autocorrelation of neighbouring nights."},
        }],
    }


INDEX_MD = """# A demonstration profile

**This is synthetic data.** A fictional person; every figure is generated by
`make_demo_profile.py` and belongs to nobody. The profile exists so that you can see a
working product before uploading data of your own.

The demo describes **a different person**, not the author of the project: a woman of 33,
a vegetarian, an amateur runner. The main line is iron deficiency without anaemia, B12
deficiency and subclinical hypothyroidism, and separately factor V Leiden against an oral
contraceptive. A picture that coincides with anybody's real profile counts as a defect of
the demo.

What it deliberately shows, besides «everything is green»:

- **ferritin 13 against a lower bound of 20 while haemoglobin is still normal** — there is a deficiency, there is no anaemia;
- **TSH 6.42 above the range, but the action threshold of 10 is not crossed** — a reference range and a threshold for action are different objects;
- **vitamin D 23.8 does not reach the sufficiency threshold of 30** — a threshold from below;
- **TIBC with no reference range** on the form: there is no flag, but that is not the same thing as a normal result;
- **MCV 99.2 at the upper bound of 100** — macrocytosis has not set in yet, but the direction matches the fall of B12;
- **the 2025-11 panel has no albumin and no alkaline phosphatase** — biological age is not computed for it;
- **three polygenic traits are marked unreliable**, each with its reason, including the case where a direct measurement matters more than a score;
- **levothyroxine and omeprazole at the same time** — the interaction is visible from the scheme rather than from memory;
- **the n-of-1 on the evening walk finished without significance**, and the naive daily p is shown next to it — twenty times smaller and entirely false.

To run:

    SCHOLION_PROFILE_DIR=demo/profile python3 -m scholion overview
    SCHOLION_PROFILE_DIR=demo/profile python3 -m scholion serve
"""


# ── assembly ───────────────────────────────────────────────────────────────
def build_all() -> dict:
    rnd = random.Random(SEED)
    return {
        "metrics.json": build_metrics(),
        "labs.json": build_labs(),
        "medications.json": build_medications(),
        "pharmacogenomics.json": build_pgx(),
        "prs_results.json": build_prs(),
        "longevity_findings.json": build_longevity(),
        "wearable_trends.json": build_wearable(rnd),
        "sleep_nightly.json": build_sleep(rnd),
        "focus.json": build_focus(),
        "studies.json": build_studies(),
        "health_goals.json": build_goals(),
        "lifestyle_brief.json": build_brief(),
        "experiments.json": build_experiments(),
    }


def occupied_by_real_profile(out: Path) -> bool:
    """Whether the directory holds data that is NOT demonstration data.

    The main danger of this script is overwriting somebody's real profile. The sign of a
    demo is the synthetic field in _meta. A file without it counts as real, because an
    error in that direction is irreversible, while in the other one it costs a --force flag.
    """
    for p in out.glob("*.json"):
        try:
            d = json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            return True
        m = d.get("_meta") or d.get("meta") or {}
        if not (isinstance(m, dict) and m.get("synthetic")):
            return True
    return False


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="scholion demo",
        description="Build a synthetic demo profile (the data are invented).")
    ap.add_argument("--out", default=None,
                    help="profile directory (demo/profile by default)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite the directory even if it holds unmarked data")
    ap.add_argument("--quiet", action="store_true")
    a = ap.parse_args(argv)

    out = Path(a.out).expanduser().resolve() if a.out else _default_out()
    if out.exists() and occupied_by_real_profile(out) and not a.force:
        print(f"✗ {out} holds data with no synthetic mark — it looks like a real profile.\n"
              f"  The demo is not written there. If you are sure it is not, repeat with --force.", file=sys.stderr)
        return 1

    out.mkdir(parents=True, exist_ok=True)
    files = build_all()
    for name, data in files.items():
        (out / name).write_text(
            json.dumps(data, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
            encoding="utf-8")
    (out / "index.md").write_text(INDEX_MD, encoding="utf-8")

    if not a.quiet:
        total = sum((out / n).stat().st_size for n in files) + (out / "index.md").stat().st_size
        print(f"✓ demo profile built: {out}")
        print(f"  {len(files) + 1} files, {total // 1024} KB, generation is deterministic (seed {SEED})")
        print()
        print("  To look at it:")
        # An absolute path is printed: a relative one holds only while the person has not
        # changed directory, and the command from the hint gets copied anywhere.
        rel = out
        print(f"    SCHOLION_PROFILE_DIR={rel} scholion overview")
        print(f"    SCHOLION_PROFILE_DIR={rel} scholion serve")
    return 0


if __name__ == "__main__":
    sys.exit(main())
