"""Rendering of engine structures into markdown strings. Used by the CLI, the Claude skill and the Ouroboros plugin.

Since 26.09.2026 this module is a facade: the renderers live in `format_*` by
screen, and every name that was reachable here still is — the CLI, the server,
the plugin and the tests call them at this address. `format_primitives` holds
what several screens share and imports nothing of ours, so the screen modules
cannot import one another in a loop."""
from __future__ import annotations

from .format_primitives import (  # noqa: F401
    NOTE_FOLD_CEILING,
    _ABBREVIATIONS,
    _FLAG_ICON,
    _LEVEL_ICON,
    _NEAR_ICON,
    _NORANGE_ICON,
    _PRIO_ICON,
    _SEV_ICON,
    _TIER_ICON,
    _clinvar_block,
    _context_lines,
    _coverage_line,
    _decision_suffix,
    _depth_span,
    _first_sentence,
    _flag_icon,
    _fmt_ref,
    _gene_coverage_note,
    _level_counts_line,
    _mark_icon,
    _n,
    _near_suffix,
    _status_mark,
    _variant_state_line,
    genotype_conclusion_lines,
    recompute_why,
    spelling_note,
)
from .format_system import (  # noqa: F401
    _names,
    _system_gene_row,
    _system_polygenic,
    _correction_route_lines,
    system_report,
    _test_row,
    systems_report,
    _panel_lines,
    evidence_levels_report,
)
from .format_labs import (  # noqa: F401
    labs_report,
    target_spec,
    _target_suffix,
    targets_report,
    metrics_report,
    reconcile_report,
    markers_report,
    fhir_report,
    import_report,
    write_result,
    draw_context_report,
    wearable_ingest_report,
    profile_set_report,
    ingest_labs_report,
    ingest_studies_report,
    markers_local_report,
)
from .format_genome import (  # noqa: F401
    _refused_head,
    _gene_region_report,
    genome_report,
    gene_layers_report,
    screen_report,
    _class_listing,
    _locus_qualifier_lines,
    _locus_basis_lines,
    _verdict_lines,
    clinvar_gene_report,
    clinvar_report,
    acmg_report,
    _prs_measurement_line,
    prs_report,
    longevity_report,
    _catalogue_size,
    genome_status_report,
    genome_updates_report,
    weak_bed_report,
    limits_report,
    lipid_genetics_report,
    array_report,
    coverage_report,
    genotype_sites_report,
    panel_report,
)
from .format_prescription import (  # noqa: F401
    drug_check,
    prescription_check,
    _pgx_mark,
    medications_report,
)
from .format_views import (  # noqa: F401
    lifestyle_report,
    goal_report,
    tests_report,
    render_brief,
    render_focus,
    overview_report,
    radar_report,
    second_opinion_report,
    goal_suggest_report,
    prevalence_report,
    brief_review_report,
)
from .format_build import (  # noqa: F401
    redact_report,
    capabilities_report,
    sources_report,
    version_report,
    version_seen_report,
    version_check_report,
    update_report,
    update_install_report,
    skill_install_report,
    skill_copies_lines,
    _RC_ICON,
    _RC_JOB_ICON,
    _clock,
    _recompute_step_line,
    recompute_plan_report,
    recompute_progress_line,
    recompute_status_report,
    recompute_run_report,
    recompute_stop_report,
)
