"""FHIR import, tested against a bundle a real system produced.

The fixture is Synthea's sample patient (Apache-2.0, synthetic data — see
ATTRIBUTION.md). That choice is the point of this file: a parser tested only on
input written by the person who wrote the parser passes its own tests and fails
on the world. This bundle was generated by software that implements the standard,
holds 137 resources of six kinds, and contains exactly the awkward things a real
export contains — observations with no numeric value, LOINC codes we do not
carry, a mixture of `effectiveDateTime` and `effectiveInstant`, and results in
US customary units that have to pass through the unit gate.

What the assertions are really about: that nothing is invented. Every observation
either becomes a point whose analyte was matched BY CODE, or appears in the
skipped list with a reason. There is no third outcome, and in particular there is
no «matched by display name», because «Glucose» in one system is not necessarily
the analyte this dictionary calls glucose.
"""
from __future__ import annotations

import json
import os
import tempfile
import unittest
from pathlib import Path

import support  # noqa: F401  — puts src/ on the import path
from scholion import core, ingest_fhir

BUNDLE = Path(__file__).resolve().parent / "fixtures" / "fhir" / "synthea_patient_clinical.json"


class FhirCase(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self._old = os.environ.get("SCHOLION_PROFILE_DIR")
        os.environ["SCHOLION_PROFILE_DIR"] = self.tmp.name
        core.reset_cache()

    def tearDown(self):
        if self._old is None:
            os.environ.pop("SCHOLION_PROFILE_DIR", None)
        else:
            os.environ["SCHOLION_PROFILE_DIR"] = self._old
        core.reset_cache()
        self.tmp.cleanup()


class TestReadingTheBundle(FhirCase):

    def test_the_fixture_is_a_bundle(self):
        got = ingest_fhir.read_bundle(BUNDLE)
        self.assertTrue(got["ok"])
        self.assertEqual(got["bundle"]["resourceType"], "Bundle")

    def test_a_single_resource_is_refused_with_its_kind_named(self):
        with tempfile.TemporaryDirectory() as tmp:
            p = Path(tmp) / "one.json"
            p.write_text(json.dumps({"resourceType": "Observation"}), encoding="utf-8")
            got = ingest_fhir.read_bundle(p)
            self.assertFalse(got["ok"])
            self.assertIn("Observation", got["error"])

    def test_unreadable_json_says_so_instead_of_raising(self):
        with tempfile.TemporaryDirectory() as tmp:
            p = Path(tmp) / "broken.json"
            p.write_text("{not json", encoding="utf-8")
            self.assertFalse(ingest_fhir.read_bundle(p)["ok"])


class TestEveryObservationIsAccountedFor(FhirCase):

    def setUp(self):
        super().setUp()
        self.plan = ingest_fhir.plan(BUNDLE)

    def test_taken_plus_skipped_equals_every_observation(self):
        self.assertEqual(len(self.plan["points"]) + len(self.plan["skipped"]),
                         self.plan["observations"],
                         "an observation that is neither taken nor named has disappeared")

    def test_every_skip_carries_a_reason(self):
        for s in self.plan["skipped"]:
            with self.subTest(label=s.get("label")):
                self.assertTrue(s.get("reason"))

    def test_the_analyte_is_matched_by_code(self):
        for p in self.plan["points"]:
            with self.subTest(key=p["key"]):
                self.assertTrue(p["loinc"], "a point without a LOINC code was matched by name")
                self.assertEqual(core.loinc_index().get(p["loinc"]), p["key"])

    def test_a_code_we_do_not_carry_is_named_rather_than_approximated(self):
        reasons = {s["reason"] for s in self.plan["skipped"]}
        self.assertIn("loinc_not_in_catalogue", reasons,
                      "this bundle does carry codes outside our dictionary — if none is "
                      "reported, something matched them by display text")

    def test_the_draw_time_keeps_its_clock(self):
        stamped = [p for p in self.plan["points"] if "T" in p["date"]]
        self.assertTrue(stamped, "the bundle states instants; a date-only stamp loses the draw time")


class TestWriting(FhirCase):

    def test_dry_run_writes_nothing(self):
        r = ingest_fhir.ingest(str(BUNDLE), dry_run=True)
        self.assertTrue(r["ok"])
        self.assertEqual(r["added"], [])
        self.assertFalse((Path(self.tmp.name) / "labs.json").exists())

    def test_the_points_reach_the_profile_through_the_unit_gate(self):
        r = ingest_fhir.ingest(str(BUNDLE))
        self.assertTrue(r["added"], "nothing was taken from a bundle that carries results")
        labs = json.loads((Path(self.tmp.name) / "labs.json").read_text(encoding="utf-8"))
        chol = labs["markers"].get("cholesterol_total")
        self.assertIsNotNone(chol, "total cholesterol is in this bundle, by code")
        # The bundle states 160.23 mg/dL. The profile keeps the project's canonical
        # unit, so the number MUST have changed on the way in.
        self.assertEqual(chol["unit"], "mmol/L")
        self.assertAlmostEqual(chol["series"][0]["value"], 4.1435, places=3)

    def test_the_patients_identity_is_reported_and_not_applied(self):
        r = ingest_fhir.ingest(str(BUNDLE))
        self.assertEqual(r["profile_facts"].get("sex"), "male")
        self.assertIsNone(core.profile_sex(),
                          "a bundle may hold a relative, a sample or two people — taking an "
                          "identity from a file is the error that contaminates everything after it")

    def test_running_twice_does_not_duplicate_the_series(self):
        ingest_fhir.ingest(str(BUNDLE))
        first = json.loads((Path(self.tmp.name) / "labs.json").read_text(encoding="utf-8"))
        ingest_fhir.ingest(str(BUNDLE))
        second = json.loads((Path(self.tmp.name) / "labs.json").read_text(encoding="utf-8"))
        for key, marker in first["markers"].items():
            with self.subTest(marker=key):
                self.assertEqual(len(second["markers"][key]["series"]), len(marker["series"]))


if __name__ == "__main__":
    unittest.main()
