"""Lifestyle, radar, briefs, focus: the living-picture cluster.

Wearable trends, the health radar, the lifestyle brief with its [[lab:..]] /
[[life:..]] / [[goal:..]] tokens, the focus dashboard, and second_opinion --
the aggregate that reads labs, drugs and lifestyle together.
"""
from __future__ import annotations

from typing import Any, Dict, List, Optional
from .. import core
from ..i18n import lang as _lang, plural as _plural, t as _t
from ._helpers import _recent, _brief_num, DISCLAIMER
from .labs import _latest, _flag_value, analyze_labs, suggest_tests
from .goals import goal_dashboard
from .pgx import check_drug_gene


# "watch" drugs for the second look (clinically frequent + relevant to the profile).
#
# These are QUERIES against the drug dictionary — but unlike a name the person typed,
# they are generated by the system, and `check_drug_gene` echoes its query back as the
# `drug` field of the answer. A fixed Russian list therefore printed Russian drug names
# into the English report: the query language leaked into the output language. Each entry
# is a language map, resolved at call time, so the report names the drug in the language
# it is being read in while the lookup still hits the same dictionary entry.
_WATCHLIST = [
    {"en": "clopidogrel",  "ru": "клопидогрел"},
    {"en": "statin",       "ru": "статин"},
    {"en": "warfarin",     "ru": "варфарин"},
    {"en": "omeprazole",   "ru": "омепразол"},
    {"en": "azathioprine", "ru": "азатиоприн"},
    {"en": "methotrexate", "ru": "метотрексат"},
]


# The label is a catalogue key, resolved when the radar is built: the key identifies the
# body system, the phrase names it in the reader's language.
_RADAR_DOMAINS = [
    ("lipids", ["cholesterol_total", "ldl", "hdl", "triglycerides"]),
    ("glucose", ["glucose", "hba1c", "homa_ir", "insulin"]),
    ("inflammation", ["crp_hs", "rheumatoid_factor", "homocysteine"]),
    ("hormones", ["testosterone", "igf1", "tsh"]),
    ("liver", ["alt", "ast", "ggt"]),
    ("micronutrients", ["vitamin_d", "omega3_index", "vitamin_b12", "ferritin"]),
    ("renal", ["uric_acid", "creatinine"]),
]


def _wear_status(latest: float, meta: Dict[str, Any]):
    """Status of a lifestyle metric vs the target. Returns (status, score 0–100 or None)."""
    d, tl, th = meta.get("direction"), meta.get("target_low"), meta.get("target_high")
    if d == "higher_better" and tl is not None:
        if latest >= tl:
            return "ok", 100
        if latest >= 0.8 * tl:
            return "warn", 70
        if latest >= 0.6 * tl:
            return "bad", 45
        return "bad", 25
    if d == "lower_better" and th is not None:
        if latest <= th:
            return "ok", 100
        if latest <= 1.2 * th:
            return "warn", 70
        if latest <= 1.5 * th:
            return "bad", 45
        return "bad", 25
    return "none", None


def lifestyle() -> Dict[str, Any]:
    """Historical lifestyle data (wearable devices): trends by year, status vs the target,
    improvement/worsening, a workout summary and an integral fitness score (for the radar/analysis)."""
    data = core.wearable_trends()
    meta = core.wearable_metrics()
    mm = meta.get("metrics", {})
    # Garmin schema: the metrics are in data["metrics"]; the old Apple schema — flat in data.
    msrc = data.get("metrics") if isinstance(data.get("metrics"), dict) else data
    def _life_metric(key, info, sd, since=None):
        """A metric from a monthly series {YYYY-MM: value}: 3-month smoothing, trend, status.

        `since` is the month from which the series is COMPARABLE WITH ITSELF. A change of
        device tears the series: an older watch counted time in bed as sleep and reported
        well over an hour more per night than the current one. Taking the "first value"
        over such a series, the application confidently reports that sleep has got worse
        by that difference — comparing two devices, not sleep. The baseline and the
        conclusion about improvement are taken from `since`; the series itself is returned
        whole, so the chart does not lie by default, but the point of reference is honest.
        """
        pts_all = sorted(({"date": y, "value": float(v)} for y, v in sd.items()), key=lambda p: p["date"])
        pts = [p for p in pts_all if p["date"] >= since] if since else pts_all
        if not pts:                       # the cut-off ate the whole series — so it is wrong
            pts, since = pts_all, None
        vals = [p["value"] for p in pts]
        smooth = [{"date": pts[i]["date"],
                   "value": round(sum(vals[max(0, i - 2):i + 1]) / len(vals[max(0, i - 2):i + 1]), 2)}
                  for i in range(len(pts))]
        latest = pts[-1]["value"]
        latest_sm, first_sm = smooth[-1]["value"], smooth[0]["value"]
        rec = None
        if len(smooth) >= 2:
            a, b = smooth[max(0, len(smooth) - 4)], smooth[-1]
            dv = round(b["value"] - a["value"], 2)
            rec = {"from": a["date"], "to": b["date"], "delta": dv,
                   "direction": "up" if dv > 0 else ("down" if dv < 0 else "flat")}
        st, score = _wear_status(latest_sm, info)
        d = info.get("direction")
        improving = (latest_sm > first_sm) if d == "higher_better" else ((latest_sm < first_sm) if d == "lower_better" else None)
        trend_good = None
        if rec and rec["direction"] != "flat" and d in ("higher_better", "lower_better"):
            up = rec["direction"] == "up"
            trend_good = up if d == "higher_better" else (not up)
        return {"key": key, "label": info.get("label", key), "unit": info.get("unit", ""),
                "comparable_from": since,
                "series_full": pts_all if since else None,
                "direction": d, "group": info.get("group", "activity"), "why": info.get("why", ""),
                "target_low": info.get("target_low"), "target_high": info.get("target_high"),
                "value": round(latest, 1), "value_smooth": latest_sm, "date": pts[-1]["date"],
                "first": round(first_sm, 1), "first_date": pts[0]["date"],
                "overall_delta": round(latest_sm - first_sm, 2),
                "improving": improving, "trend_good": trend_good, "status": st, "score": score,
                "trend": rec, "series": pts, "smooth": smooth}

    # The month from which each series is comparable with itself. It lives in the profile
    # and not in the public metrics reference: the date a device was changed is a fact of
    # the owner's biography, not a property of the metric. No key — previous behaviour.
    cmp_from = (data.get("_meta") or {}).get("comparable_from") or {}
    out = []
    for key in meta.get("order", list(mm.keys())):
        sd = msrc.get(key)
        if isinstance(sd, dict) and sd:
            out.append(_life_metric(key, mm.get(key, {"label": key}), sd, cmp_from.get(key)))
    # manual markers from metrics.json that are NOT in Garmin (e.g. waist/measurements) — also with a trend
    _SKIP = {"weight", "steps", "resting_hr", "sleep_hours", "activity_min"}   # covered by Garmin
    for mk, marker in (core.metrics_json().get("metrics", {}) or {}).items():
        if mk in _SKIP or not marker.get("series"):
            continue
        buckets: Dict[str, List[float]] = {}
        for p in marker["series"]:
            mo = str(p.get("date", ""))[:7]
            if len(mo) == 7 and isinstance(p.get("value"), (int, float)):
                buckets.setdefault(mo, []).append(p["value"])
        monthly = {mo: round(sum(v) / len(v), 1) for mo, v in buckets.items()}
        if not monthly:
            continue
        direction = marker.get("direction") or ("lower_better" if marker.get("ref_high")
                                                else ("higher_better" if marker.get("ref_low") else None))
        info = {"label": marker.get("name", mk), "unit": marker.get("unit", ""),
                "direction": direction, "group": "anthro", "why": marker.get("note", ""),
                "target_high": marker.get("ref_high"), "target_low": marker.get("ref_low")}
        out.append(_life_metric(mk, info, monthly))
    # workouts: totals by type + the last active year
    workouts = []
    wnew = data.get("workouts")
    wold = data.get("Workouts")
    if isinstance(wnew, dict):
        # Garmin: {year: {label: {count, hours}}} → aggregated by label
        agg: Dict[str, Dict[str, Any]] = {}
        for yr, types in wnew.items():
            if not isinstance(types, dict):
                continue
            for typ, v in types.items():
                cnt = (v.get("count", 0) if isinstance(v, dict) else v) or 0
                hrs = (v.get("hours", 0) if isinstance(v, dict) else 0) or 0
                a = agg.setdefault(typ, {"total": 0, "hours": 0.0, "last_year": yr, "last_count": 0})
                a["total"] += cnt; a["hours"] += hrs
                if yr >= a["last_year"]:
                    a["last_year"] = yr; a["last_count"] = cnt
        for typ, a in agg.items():
            workouts.append({"type": typ, "total": a["total"], "hours": round(a["hours"], 1),
                             "last_year": a["last_year"], "last_count": a["last_count"]})
        workouts.sort(key=lambda x: -x["total"])
    elif isinstance(wold, dict):
        # the old Apple schema: {type: {year: count}}
        for typ, yrs in wold.items():
            if not isinstance(yrs, dict) or not yrs:
                continue
            ly = max(yrs.keys())
            workouts.append({"type": typ, "total": sum(yrs.values()), "last_year": ly, "last_count": yrs.get(ly)})
        workouts.sort(key=lambda x: -x["total"])
    scored = [m["score"] for m in out if m.get("score") is not None]
    fitness = round(sum(scored) / len(scored)) if scored else None

    # conclusions for the strategy (metabolic syndrome: bring weight/fat down, raise activity,
    # keep muscle, improve recovery) — from the 3-month trend of the key metrics
    _KEY = ("Weight", "BodyFat", "MuscleMass", "VO2Max", "IntensityMinutesDaily",
            "StepsDaily", "HRV", "BodyBatteryHigh", "RestingHeartRate")
    by_key = {m["key"]: m for m in out}
    good, watch = [], []
    for k in _KEY:
        lbl = _t(f"lifestyle.metric.{k}")
        m = by_key.get(k)
        if not m or not m.get("trend") or m["trend"]["direction"] == "flat":
            continue
        arrow = "↑" if m["trend"]["direction"] == "up" else "↓"
        item = {"label": lbl, "value": m["value"], "unit": m["unit"],
                "delta": m["trend"]["delta"], "arrow": arrow}
        if m.get("trend_good") is True:
            good.append(item)
        elif m.get("trend_good") is False:
            watch.append(item)
    conclusions = {"good": good, "watch": watch}
    return {"metrics": out, "workouts": workouts[:14], "fitness_score": fitness,
            "conclusions": conclusions, "disclaimer": DISCLAIMER()}


def _prev_point(series) -> Optional[Dict[str, Any]]:
    """The next-to-last point of a series (the previous measurement) or None."""
    if not series or len(series) < 2:
        return None
    return sorted(series, key=lambda p: p["date"])[-2]


def _marker_health_at(key: str, point: Optional[Dict[str, Any]]) -> Optional[int]:
    """Health score of a marker computed at an ARBITRARY point of the series (usually the previous one)."""
    raw = core.labs().get("markers", {}).get(key)
    if not raw or not point:
        return None
    flag = _flag_value(raw, point["value"], point.get("censored"))
    return _marker_health({"flag": flag, "value": point["value"],
                           "ref_low": raw.get("ref_low"), "ref_high": raw.get("ref_high")})


def _marker_health(m: Dict[str, Any]) -> int:
    """A 0–100 score for one marker: 100 within range, less — by the DEGREE of deviation.
    That way the radar becomes selective (it does not collapse to 0), and a mild deviation
    differs from a severe one."""
    if m.get("flag") == "ok":
        return 100
    v = m.get("value")
    lo, hi = m.get("ref_low"), m.get("ref_high")
    frac = None  # the relative excess over the bound
    try:
        if m.get("flag") == "high" and hi:
            frac = (v - hi) / abs(hi)
        elif m.get("flag") == "low" and lo:
            frac = (lo - v) / abs(lo)
    except Exception:
        frac = None
    if frac is None:
        return 55  # there is a deviation, but its scale cannot be assessed
    frac = max(frac, 0.0)
    # gradation by the size of the deviation from the reference bound
    if frac <= 0.15:
        return 75
    if frac <= 0.40:
        return 60
    if frac <= 0.90:
        return 45
    if frac <= 2.0:
        return 30
    return 15


def health_radar() -> Dict[str, Any]:
    """Assessment by body system (for the radar): 0–100 as the MEAN health score of the
    system's markers, accounting for the degree of deviation (and not for the share within range)."""
    labs = analyze_labs()
    by_key = {m["key"]: m for m in labs["markers"]}
    domains = []
    for key, keys in _RADAR_DOMAINS:
        label = _t(f"radar.domain.{key}")
        present = [by_key[k] for k in keys if k in by_key]
        if not present:
            domains.append({"key": key, "label": label, "score": None, "status": "nodata",
                            "prev_score": None, "compared_score": None, "delta": None,
                            "prev_date": None, "compared": 0, "moved": [],
                            "total": len(keys), "measured": 0, "missing": list(keys),
                            "ok": 0, "abnormal": []})
            continue
        scores = [_marker_health(m) for m in present]
        abn = [m for m in present if m["flag"] != "ok"]
        score = round(sum(scores) / len(scores))
        status = "good" if score >= 80 else ("warning" if score >= 55 else "critical")
        # --- dynamics: ONLY the markers that have a previous point are compared,
        # otherwise the means would be computed over different sets of markers ---
        comp = []
        for m in present:
            raw = core.labs().get("markers", {}).get(m["key"], {})
            pp = _prev_point(raw.get("series"))
            ph = _marker_health_at(m["key"], pp)
            if ph is None:
                continue
            comp.append({"key": m["key"], "name": m["name"], "unit": m.get("unit", ""),
                         "cur": _marker_health(m), "prev": ph,
                         "from_date": pp["date"], "to_date": m.get("date"),
                         "from_value": pp["value"], "to_value": m.get("value")})
        prev_score = delta = prev_date = compared_score = None
        moved = []
        if comp:
            # Both ends of the comparison are means over the SAME markers — the ones
            # that actually have a previous point. What stood here was
            # `max(0, min(100, score - delta))`: the domain's current score, computed
            # over every measured marker, minus a delta computed over the smaller
            # compared subset. The result was a number nobody had measured, printed
            # with a date beside it — «in January the index was 100/100» out of the
            # movement of a single marker.
            cur_c = sum(c["cur"] for c in comp) / len(comp)
            prev_c = sum(c["prev"] for c in comp) / len(comp)
            delta = round(cur_c - prev_c)
            prev_score = round(prev_c)
            compared_score = round(cur_c)
            prev_date = max(c["from_date"] for c in comp)
            moved = sorted([c for c in comp if c["cur"] != c["prev"]],
                           key=lambda c: -abs(c["cur"] - c["prev"]))[:4]
        domains.append({
            "key": key, "label": label, "score": score, "status": status,
            "prev_score": prev_score, "compared_score": compared_score,
            "delta": delta, "prev_date": prev_date,
            "compared": len(comp), "moved": moved,
            # `total` is the panel the domain DECLARES, not the part of it that
            # happens to be measured. With `len(present)` a domain announced by four
            # markers, of which one had ever been drawn, printed «🟢 100/100, 0 out
            # of range of 1» — a statement about a body system made from a quarter
            # of it. The declared size is the denominator; `measured` says how much
            # of it the statement actually rests on.
            "total": len(keys), "measured": len(present),
            "missing": [k for k in keys if k not in by_key],
            "ok": len(present) - len(abn),
            "abnormal": [{"key": m["key"], "name": m["name"], "value": m["value"], "unit": m["unit"],
                          "flag": m["flag"], "ref_low": m["ref_low"], "ref_high": m["ref_high"],
                          "date": m.get("date"), "stale": not _recent(m.get("date"), 18),
                          "note": m.get("note"), "genome_link": m.get("genome_link")}
                         for m in abn],
        })
    # + the "Fitness" domain from lifestyle (wearable devices) — so that it counts in the analysis
    try:
        ls = lifestyle()
        if ls.get("fitness_score") is not None:
            sc = ls["fitness_score"]
            fstatus = "good" if sc >= 80 else ("warning" if sc >= 55 else "critical")
            fab = []
            for m in ls["metrics"]:
                if m.get("status") in ("warn", "bad"):
                    flag = "high" if m.get("direction") == "lower_better" else "low"
                    fab.append({"key": m["key"], "name": m["label"], "value": m["value"], "unit": m["unit"],
                                "flag": flag, "ref_low": None, "ref_high": None, "stale": False,
                                "note": m.get("why"), "genome_link": None})
            fcomp = []
            for m in ls["metrics"]:
                sm = m.get("smooth") or []
                if len(sm) < 2 or m.get("score") is None:
                    continue
                _st, ps = _wear_status(sm[-2]["value"], m)
                if ps is None:
                    continue
                fcomp.append({"key": m["key"], "name": m["label"], "unit": m.get("unit", ""),
                              "cur": m["score"], "prev": ps,
                              "from_date": sm[-2]["date"], "to_date": sm[-1]["date"],
                              "from_value": sm[-2]["value"], "to_value": sm[-1]["value"]})
            fprev = fdelta = fpdate = fcur = None
            fmoved = []
            if fcomp:
                cur_c = sum(c["cur"] for c in fcomp) / len(fcomp)
                prev_c = sum(c["prev"] for c in fcomp) / len(fcomp)
                fdelta = round(cur_c - prev_c)
                fprev = round(prev_c)          # measured, over the same metrics as the delta
                fcur = round(cur_c)
                fpdate = max(c["from_date"] for c in fcomp)
                fmoved = sorted([c for c in fcomp if c["cur"] != c["prev"]],
                                key=lambda c: -abs(c["cur"] - c["prev"]))[:4]
            domains.append({"key": "fitness", "label": _t("radar.domain.fitness"),
                            "score": sc, "status": fstatus,
                            "prev_score": fprev, "compared_score": fcur,
                            "delta": fdelta, "prev_date": fpdate,
                            "compared": len(fcomp), "moved": fmoved,
                            # every wearable metric of the domain is measured by
                            # construction — there is no unmeasured remainder here
                            "total": len(ls["metrics"]), "measured": len(ls["metrics"]),
                            "missing": [],
                            "ok": sum(1 for m in ls["metrics"] if m.get("status") == "ok"), "abnormal": fab})
    except Exception:
        pass

    scored = [d for d in domains if d["score"] is not None]
    overall = round(sum(d["score"] for d in scored) / len(scored)) if scored else None
    withprev = [d for d in scored if d.get("prev_score") is not None]
    prev_overall = overall_delta = prev_date = None
    if withprev and overall is not None:
        # Same rule one level up: both ends over the same domains.
        overall_delta = round(sum(d["compared_score"] for d in withprev) / len(withprev)
                              - sum(d["prev_score"] for d in withprev) / len(withprev))
        prev_overall = round(sum(d["prev_score"] for d in withprev) / len(withprev))
        prev_date = max(d["prev_date"] for d in withprev if d.get("prev_date"))
    return {"domains": domains, "overall": overall, "prev_overall": prev_overall,
            "overall_delta": overall_delta, "prev_date": prev_date,
            "disclaimer": DISCLAIMER()}


def _lifestyle_overview() -> Optional[Dict[str, Any]]:
    try:
        ls = lifestyle()
    except Exception:
        return None
    if not ls.get("metrics"):
        return None
    watch = [{"label": m["label"], "value": m["value"], "unit": m["unit"], "status": m["status"]}
             for m in ls["metrics"] if m.get("status") == "bad"]
    return {"fitness_score": ls.get("fitness_score"), "watch": watch[:4]}


def second_opinion() -> Dict[str, Any]:
    """Composition: the labs (red) + the pharmacogenetics watchlist + the suggested tests."""
    labs = analyze_labs()
    drugs = [check_drug_gene(core._localized(d, _lang())) for d in _WATCHLIST]
    flagged_drugs = [d for d in drugs if d.get("status") == "ok" and d.get("level") in ("high", "moderate", "unknown")]
    tests = suggest_tests()
    # How much of this section is a statement about the person, and how much is the
    # general rule printed because there was no genotype to apply. Each entry says so
    # for itself, but the reader meets the SECTION first, and a section that opens
    # with seven drug names reads as seven findings. The counts travel with the list
    # so the output layer can say which it is before the list begins.
    return {
        "red_labs": [m for m in labs["markers"] if m["flag"] != "ok"],
        "drug_flags": flagged_drugs,
        "drugs_checked": len(drugs),
        "drugs_answerable": sum(1 for d in drugs if d.get("status") == "ok"
                                and d.get("certainty") not in (None, "unknown")),
        "suggestions": tests["suggestions"],
        "suggestions_pending": tests["count"],
        "disclaimer": DISCLAIMER(),
    }


# ============================ Lifestyle brief ================================
# A hybrid: the numbers come from live data (tokens), the wording from profile/lifestyle_brief.json,
# the freshness is computed from the watch lists. For details see SKILL.md, scenario E.

_BRIEF_TOKEN = __import__("re").compile(r"\[\[(lab|life|goal):([A-Za-z0-9_.\- ]+)\]\]")


def _brief_lab(key: str) -> Dict[str, Any]:
    m = (core.labs().get("markers") or {}).get(key)
    if not m:
        return {"text": _t("brief.no_marker", key=key), "date": None, "status": "missing"}
    pt = _latest(m.get("series") or [])
    if not pt:
        return {"text": _t("brief.no_data"), "date": None, "status": "missing"}
    val, unit = pt.get("value"), (m.get("unit") or "")
    lo, hi = m.get("ref_low"), m.get("ref_high")
    status = "ok"
    try:
        if lo is not None and float(val) < float(lo):
            status = "low"
        elif hi is not None and float(val) > float(hi):
            status = "high"
    except (TypeError, ValueError):
        status = "unknown"
    if lo is not None and hi is not None:
        ref = _t("brief.ref_range", low=_brief_num(lo), high=_brief_num(hi))
    elif hi is not None:
        ref = _t("brief.ref_max", high=_brief_num(hi))
    elif lo is not None:
        ref = _t("brief.ref_min", low=_brief_num(lo))
    else:
        ref = ""
    return {"text": f"{_brief_num(val)} {unit}{ref}".strip(), "value": val,
            "date": pt.get("date"), "name": m.get("name") or key, "status": status}


def _brief_life(key: str) -> Dict[str, Any]:
    try:
        ls = lifestyle()
    except Exception:                                            # noqa: BLE001
        return {"text": _t("brief.no_metric", key=key), "date": None, "status": "missing"}
    for m in ls.get("metrics", []):
        if m.get("key") == key or m.get("label") == key:
            return {"text": f"{_brief_num(m.get('value'))} {m.get('unit') or ''}".strip(),
                    "value": m.get("value"), "date": m.get("date"),
                    "status": m.get("status") or "ok"}
    return {"text": _t("brief.no_metric", key=key), "date": None, "status": "missing"}


def _brief_goal(label: str) -> Dict[str, Any]:
    try:
        g = goal_dashboard()
    except Exception:                                            # noqa: BLE001
        return {"text": "—", "date": None, "status": "missing"}
    for t in g.get("targets", []):
        if str(t.get("label", "")).lower().startswith(label.lower()):
            return {"text": _t("brief.goal_now", now=t.get('now'), target=t.get('target')),
                    "value": t.get("now"), "date": g.get("as_of"), "status": "ok"}
    return {"text": "—", "date": None, "status": "missing"}


def _brief_resolve(text: str) -> Dict[str, Any]:
    used: List[Dict[str, Any]] = []
    fn = {"lab": _brief_lab, "life": _brief_life, "goal": _brief_goal}

    def sub(m):
        kind, key = m.group(1), m.group(2)
        d = fn[kind](key)
        used.append({"kind": kind, "key": key, "date": d.get("date"),
                     "status": d.get("status"), "value": d.get("text")})
        return d["text"]

    return {"text": _BRIEF_TOKEN.sub(sub, text or ""), "used": used}


def _brief_newest(watch: List[Dict[str, Any]]) -> Optional[str]:
    """The most recent date among the block's watched markers."""
    markers = core.labs().get("markers") or {}
    best = None
    for w in watch or []:
        if w.get("kind") not in (None, "lab"):
            continue
        pt = _latest((markers.get(w.get("key")) or {}).get("series") or [])
        d = (pt or {}).get("date")
        if d and (best is None or d > best):
            best = d
    return best


def _brief_snapshot_item(s: Dict[str, Any]) -> Dict[str, Any]:
    """A snapshot row "now → goal": the text + the NUMBER and the scale for the bullet bar.

    The numeric value is obtained by the same resolver as the text — there is one source,
    so a discrepancy between the caption and the bar is impossible.
    """
    tok = s.get("token") or ""
    r = _brief_resolve(tok)
    used = (r["used"] or [{}])[0]
    kind, key = used.get("kind"), used.get("key")
    raw = None
    if kind == "lab":
        raw = _brief_lab(key).get("value")
    elif kind == "life":
        raw = _brief_life(key).get("value")
    try:
        raw = float(raw) if raw is not None else None
    except (TypeError, ValueError):
        raw = None
    return {"label": s.get("label"), "value": r["text"], "raw": raw,
            "unit": s.get("unit") or "", "min": s.get("min"), "max": s.get("max"),
            "target_value": s.get("target_value"), "dir": s.get("dir") or "lower",
            "date": used.get("date"), "status": used.get("status"),
            "target": s.get("target") or "", "tone": s.get("tone") or "muted",
            "source": s.get("source"), "note": s.get("note") or ""}


def lifestyle_brief() -> Dict[str, Any]:
    """Lifestyle brief: live numbers + curated wording + a freshness flag."""
    src = core.lifestyle_brief_src() or {}
    blocks_in = src.get("blocks") or []
    if not blocks_in:
        return {"available": False,
                "reason": _t("brief.not_available")}
    order = src.get("sections") or []
    sections: Dict[str, Dict[str, Any]] = {
        s["id"]: {"id": s["id"], "title": s.get("title") or s["id"],
                  "lead": s.get("lead") or "", "blocks": []} for s in order}
    stale: List[Dict[str, Any]] = []
    for b in blocks_in:
        r = _brief_resolve(b.get("body") or "")
        newest = _brief_newest(b.get("watch") or [])
        reviewed = b.get("reviewed")
        is_stale = bool(newest and reviewed and newest > reviewed)
        item = {"id": b.get("id"), "title": b.get("title") or "", "body": r["text"],
                "sources": r["used"], "watch": b.get("watch") or [], "reviewed": reviewed,
                "newest_data": newest, "stale": is_stale,
                "review_hint": b.get("review_hint") or "", "weight": b.get("weight", 5)}
        if is_stale:
            stale.append({"id": b.get("id"), "title": b.get("title"),
                          "reviewed": reviewed, "newest_data": newest,
                          "review_hint": b.get("review_hint") or ""})
        sec = sections.setdefault(b.get("section") or "other",
                                  {"id": b.get("section") or "other",
                                   "title": _t("brief.section_other"), "lead": "", "blocks": []})
        sec["blocks"].append(item)
    for s in sections.values():
        s["blocks"].sort(key=lambda x: -x.get("weight", 5))
    ordered = [sections[s["id"]] for s in order if s["id"] in sections]
    ordered += [v for k, v in sections.items() if k not in {s["id"] for s in order}]
    return {"available": True,
            "title": src.get("title") or _t("brief.title_default"),
            "subtitle": _brief_resolve(src.get("subtitle") or "")["text"],
            "compiled": src.get("compiled"),
            "disclaimer": src.get("disclaimer") or _t("disclaimer.short"),
            "snapshot": [_brief_snapshot_item(s) for s in (src.get("snapshot") or [])],
            "sections": [s for s in ordered if s["blocks"]],
            "actions": [_brief_resolve(a)["text"] for a in (src.get("actions") or [])],
            "dropped": src.get("dropped") or [],
            "stale_blocks": stale,
            "needs_review": bool(stale)}


# ============================ FOCUS OF ATTENTION =============================
# The one task the owner is concentrated on right now. The curated part lies in
# profile/focus.json; the LIVE numbers are computed here: where the metric is now,
# what happens with the levers over the last window and what the episode journal gives.
# It prescribes nothing: the levers are observations on one's own data, questions go to the doctor.

def _focus_nights(days: Optional[int] = None) -> List[Dict[str, Any]]:
    """Per-night records with phases, newer than PHASES_FROM, and if required — the last `days`."""
    nights = [n for n in (core.sleep_nightly().get("nights") or [])
              if (n.get("date") or "") >= "2022-01-01" and n.get("deep_min")]
    nights.sort(key=lambda n: n["date"])
    if days and nights:
        import datetime as _d
        try:
            edge = (_d.date.fromisoformat(nights[-1]["date"]) - _d.timedelta(days=days)).isoformat()
            nights = [n for n in nights if n["date"] >= edge]
        except ValueError:
            pass
    return nights


def _focus_mean(xs) -> Optional[float]:
    xs = [x for x in xs if isinstance(x, (int, float))]
    return round(sum(xs) / len(xs), 1) if xs else None


def _focus_metric(metric: Dict[str, Any]) -> Dict[str, Any]:
    """Where the metric is now: the latest monthly value + the mean over 30/90 nights."""
    key = metric.get("key") or ""
    cur = _brief_life(key) if metric.get("kind") == "life" else _brief_lab(key)
    n30, n90 = _focus_nights(30), _focus_nights(90)
    field = "deep_min" if key == "DeepSleepMin" else None
    out = {"label": metric.get("label"), "unit": metric.get("unit"),
           "dir": metric.get("dir", "higher"),
           "value": cur.get("value"), "raw": cur.get("raw"), "as_of": cur.get("date"),
           "baseline": metric.get("baseline"), "baseline_note": metric.get("baseline_note"),
           "target": metric.get("target"), "target_source": metric.get("target_source"),
           "target_note": metric.get("target_note"),
           "mean_30": _focus_mean([n.get(field) for n in n30]) if field else None,
           "mean_90": _focus_mean([n.get(field) for n in n90]) if field else None,
           "nights_30": len(n30), "nights_90": len(n90),
           # The window bounds matter: the Garmin export is static, so "the last 30 nights"
           # means the last 30 nights OF THE EXPORT, not the last 30 calendar days.
           "window_from": n30[0]["date"] if n30 else None,
           "window_to": n30[-1]["date"] if n30 else None}
    # The numbers are shown in the Russian notation (comma), as everywhere in the application.
    out["mean_30_txt"] = _brief_num(out["mean_30"])
    out["mean_90_txt"] = _brief_num(out["mean_90"])
    out["baseline_txt"] = _brief_num(out["baseline"])
    out["target_txt"] = _brief_num(out["target"])
    base, m30 = out["baseline"], out["mean_30"]
    if isinstance(base, (int, float)) and isinstance(m30, (int, float)):
        out["delta"] = round(m30 - base, 1)
        out["delta_txt"] = ("+" if out["delta"] > 0 else "") + _brief_num(out["delta"])
        # The 2-minute threshold is not statistics but an honest limit of discernibility:
        # deep sleep scatters by ±15 min between nights, a monthly mean over 30 nights is noisy at units.
        out["direction"] = _t("focus.direction.up" if out["delta"] >= 2 else
                              "focus.direction.down" if out["delta"] <= -2
                              else "focus.direction.flat")
    return out


def _focus_lever_check(check: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    """A live measurement of a lever over the observation window. None — the lever is not measured automatically."""
    if not check:
        return None
    if not isinstance(check, dict):
        # The profile is edited by hand. A string instead of an object is no reason to
        # take the whole tab down: the lever is then not measured automatically.
        return None
    kind = check.get("kind")
    win = int(check.get("window") or 30)
    nights = _focus_nights(win)
    if not nights:
        return None
    if kind == "bedtime_share":
        thr = float(check.get("threshold") or 310)
        vals = [n.get("bedtime_min_from_20") for n in nights
                if isinstance(n.get("bedtime_min_from_20"), (int, float))]
        if not vals:
            return None
        share = round(100 * sum(1 for v in vals if v <= thr) / len(vals))
        avg = _focus_mean(vals)
        return {"text": _t("focus.bedtime_share", n=len(vals), share=share,
                           clock=_focus_clock(avg)),
                "share": share, "mean": avg, "n": len(vals)}
    if kind == "awake_mean":
        vals = [n.get("awake_min") for n in nights if isinstance(n.get("awake_min"), (int, float))]
        if not vals:
            return None
        return {"text": _t("focus.awake_mean", n=len(vals),
                           mean=_brief_num(_focus_mean(vals))),
                "mean": _focus_mean(vals), "n": len(vals)}
    if kind == "journal_alcohol":
        return _focus_journal_split(win)
    return None


def _focus_clock(mins: Optional[float]) -> str:
    """Minutes from 20:00 → hours:minutes of local time."""
    if not isinstance(mins, (int, float)):
        return "—"
    total = (20 * 60 + int(round(mins))) % (24 * 60)
    return f"{total // 60:02d}:{total % 60:02d}"


def _focus_journal_split(window: int = 120) -> Dict[str, Any]:
    """Separate the superimposed factors with the journal: clean / alcohol / alcohol + atenolol.

    The point of this computation is not to "prove harm" but to SEPARATE what is inseparable
    in passive data: the drug is taken on exactly the evenings when there is alcohol.
    While the episodes are few, "not enough data" is returned honestly instead of a number.
    """
    entries = {e.get("date"): e for e in (core.focus_log().get("entries") or []) if e.get("date")}
    nights = {n["date"]: n for n in _focus_nights(window)}
    groups: Dict[str, List[float]] = {"clean": [], "alcohol": [], "alcohol_atenolol": []}
    for date, n in nights.items():
        e = entries.get(date) or {}
        alc = bool(e.get("alcohol"))
        aten = bool(e.get("atenolol"))
        key = "alcohol_atenolol" if (alc and aten) else "alcohol" if alc else "clean"
        groups[key].append(n["deep_min"])
    logged = sum(1 for d in entries if d in nights)
    res = {"kind": "journal", "window": window, "logged_nights": logged,
           "groups": [{"id": k, "n": len(v), "mean": _focus_mean(v)} for k, v in groups.items()]}
    need = 8
    if len(groups["alcohol"]) < need or len(groups["alcohol_atenolol"]) < need:
        res["ready"] = False
        res["text"] = _t("focus.journal_not_ready",
                         nights=_plural(logged, "count.nights"), need=need,
                         a=len(groups['alcohol']), b=len(groups['alcohol_atenolol']))
    else:
        res["ready"] = True
        a, b = _focus_mean(groups["alcohol"]), _focus_mean(groups["alcohol_atenolol"])
        res["text"] = _t("focus.journal_split", a=a, b=b,
                         delta=round((b or 0) - (a or 0), 1))
    return res


def _focus_evidence() -> Dict[str, Any]:
    """What has ALREADY been done instrumentally on the focus topic — and what is left open.

    It is needed exactly so as not to suggest a study that is already in the profile.
    The assistant reads prose selectively; the engine reads it always.
    """
    st = (core.studies().get("studies") or [])
    done, open_items = [], []
    for s in st:
        done.append({"date": s.get("date"), "kind": s.get("kind"),
                     "conclusion": s.get("conclusion"),
                     "answers": s.get("answers") or [],
                     "does_not_answer": s.get("does_not_answer") or [],
                     "source": s.get("source")})
        for o in s.get("open") or []:
            open_items.append({"from": s.get("kind"), "date": s.get("date"),
                               "what": o.get("what"), "note": o.get("note")})
    return {"studies": done, "open": open_items, "count": len(done)}


def focus_dashboard() -> Dict[str, Any]:
    """Focus of attention: the goal, the live metric, the state of the levers, the journal, the questions."""
    src = core.focus_src() or {}
    f = src.get("focus") or {}
    if not f:
        return {"available": False,
                "reason": _t("focus.not_set_reason")}
    levers = []
    for lv in f.get("levers") or []:
        levers.append({"id": lv.get("id"), "title": lv.get("title"),
                       "status": lv.get("status") or "secondary",
                       "expected": lv.get("expected") or "",
                       "evidence": lv.get("evidence") or "",
                       "now": _focus_lever_check(lv.get("check"))})
    jr = f.get("journal") or {}
    split = _focus_journal_split(int(jr.get("window") or 120))
    return {"available": True,
            "id": f.get("id"), "title": f.get("title"), "started": f.get("started"),
            "why": f.get("why") or "",
            "metric": _focus_metric(f.get("metric") or {}),
            "levers": levers,
            "journal": {**jr, "state": split},
            "questions": f.get("questions") or [],
            "evidence": _focus_evidence(),
            # The owner's four goals (2026-08-14). The main task stays in `focus`,
            # but the list of goals is wider, and it must not be lost.
            "tracks": src.get("tracks") or [],
            "done": f.get("done") or [],
            "updated": (src.get("_meta") or {}).get("updated"),
            "disclaimer": (src.get("_meta") or {}).get("disclaimer") or _t("disclaimer.short")}
