#!/usr/bin/env python3
"""What this build knows, compared with what it ought to — three enumerators.

    python3 src/tools/check_coverage.py            # print the gaps
    python3 src/tools/check_coverage.py --strict   # exit 1 if a NEW gap appeared
    python3 src/tools/check_coverage.py --accept   # take the current gaps as the baseline

Why this file exists.

Four defects were repaired one at a time in this series: an activity-score model
that had drifted from the source, a drug dosed by two genes where only one was
modelled, a diplotype the pipeline computed and the reasoning layer never read,
and a phenotype the model could produce for which the table had no row. They
were found by people — an outside audit, then a careful reading. Repairing each
one leaves the class intact: nothing in the build could have said «here is the
next one», and the next one would again have waited for a person to be harmed by
it or lucky enough to notice.

Every one of those four is the same shape: THE SYSTEM HELD TWO FACTS AND
COMPARED NEITHER WITH THE OTHER. It held a transcribed table and an upstream
table; a drug's gene and the authority's list of that drug's genes; a field
written by the pipeline and the fields the engine reads; a phenotype the model
can emit and the phenotypes the guidance answers. So the general repair is not a
fifth fix, it is comparison made mechanical and continuous:

  A. ORPHAN FACTS   — a field the pipeline writes into the profile that no engine
                      code reads. (The class the audit named the system cause.)
  B. COVERAGE HOLES — a phenotype a gene model can produce for which the drug's
                      guidance has no entry, so the answer silently falls back to
                      `default`. (The codeine PM class.)
  C. AUTHORITY DELTA — a gene↔drug pair CPIC calls actionable at level A that
                      this build does not carry, or carries with fewer genes than
                      CPIC names for it. (The NUDT15 class.)

The gate is the project's existing idiom, borrowed from the language remainder:
known gaps are recorded in a baseline and listed out loud; a NEW gap fails the
build. Coverage is never claimed to be complete — it is stated as a fraction,
with the missing part enumerated. A gap that is written down is a decision; a
gap that nobody enumerated is a false claim of completeness.
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "src"
sys.path.insert(0, str(SRC))
KNOWLEDGE = SRC / "scholion" / "knowledge"
BASELINE = ROOT / "src" / "tools" / "coverage_baseline.json"

def _load(name):
    return json.loads((KNOWLEDGE / name).read_text(encoding="utf-8"))


# ---------------------------------------------------------------- A: orphans
def orphan_facts():
    """Fields written into a profile that no engine code reads.

    The demo profile is the inventory: it is generated by the same writers as a
    real one and carries every key the pipeline can produce. A key that appears
    nowhere in the reading code is a fact computed and thrown away — which is
    exactly how a called CYP2D6 diplotype sat unused in the file while the report
    said the gene could not be assessed.
    """
    from scholion import demo
    code = "\n".join(p.read_text(encoding="utf-8", errors="ignore")
                     for p in (SRC / "scholion").rglob("*.py")
                     if p.name not in ("demo.py",) and not p.name.startswith("check_"))
    # Every build_* function in demo.py produces one profile file, using the same
    # writers a real profile goes through — so together they are the inventory of
    # every key the pipeline can put on disk. Discovered by name rather than
    # listed, so a new writer is included the day it is added.
    profile = {}
    for name in dir(demo):
        if not name.startswith("build_"):
            continue
        fn = getattr(demo, name)
        if not callable(fn):
            continue
        try:
            out = fn()
        except TypeError:
            try:
                import random
                out = fn(random.Random(0))
            except Exception:
                continue
        except Exception:
            continue
        if isinstance(out, dict):
            profile[name[len("build_"):]] = out
    if not profile:
        raise SystemExit("check_coverage: the demo writers produced nothing — this "
                         "enumerator would silently report zero orphans forever. "
                         "Fix the discovery above rather than trusting the zero.")
    out = []

    def is_collection(node):
        """A map whose KEYS are data, not schema.

        `labs.markers` is keyed by marker name, `genotypes` by rsid: those keys
        are contents, read by iteration and never by literal name, so demanding
        that the code mention each one would report five hundred orphans and
        bury the one that matters. A schema map has few, fixed keys; a
        collection has many keys whose values share a shape.
        """
        if not isinstance(node, dict) or len(node) < 5:
            return False
        vals = [v for v in node.values() if isinstance(v, dict)]
        if len(vals) < len(node) * 0.8:
            return False
        shapes = {frozenset(v.keys()) for v in vals}
        return len(shapes) <= max(2, len(vals) // 3)

    def walk(node, path, depth=0):
        if depth > 3 or not isinstance(node, dict):
            return
        if is_collection(node):
            # the keys are data — check the SHAPE of one entry instead
            first = next(iter(node.values()), None)
            walk(first, f"{path}.<each>", depth + 1)
            return
        for k, v in node.items():
            if k.startswith("_") or k == "meta":
                continue
            if re.fullmatch(r"\d{4}(-\d{2}){0,2}", str(k)):
                continue          # a date is data, whatever its container looks like
            here = f"{path}.{k}" if path else k
            if not re.search(r"[\"']" + re.escape(k) + r"[\"']", code):
                out.append(here)
                continue
            walk(v, here, depth + 1)

    for fname, content in profile.items():
        if fname != "all":
            continue          # build_all() already contains every writer's output
        if isinstance(content, dict):
            # build_all() returns {filename: content}; unwrap so paths read as
            # «pharmacogenomics.hla», not «all.pharmacogenomics.json.hla»
            for real, body in content.items():
                walk(body, str(real).replace(".json", ""))
            continue
    return sorted(set(out))


# --------------------------------------------------------- B: coverage holes
def coverage_holes():
    """A phenotype a gene can emit for which the drug's table has no row.

    The vocabulary is READ from the gene's own `emits` declaration rather than
    guessed from the model's name. Guessing is how the first draft of this file
    reported five holes in fluorouracil that were really one mismatch, and missed
    that the mismatch was the point. A row absent on purpose (`guidance_gaps`)
    is not a hole — it is a decision, and it is listed separately.
    """
    kb = _load("cpic_drug_gene.json")
    genes = kb.get("genes", {})
    out = []
    for drug in kb.get("drugs", []):
        gene = drug.get("gene")
        emits = (genes.get(gene) or {}).get("emits") or []
        if not emits:
            continue
        guidance = drug.get("guidance") or {}
        declared = set(drug.get("guidance_gaps") or {})
        name = drug["names"][1] if len(drug["names"]) > 1 else drug["names"][0]
        for ph in emits:
            if ph not in guidance and ph not in declared:
                out.append(f"{name} ({gene}): no guidance for {ph}")
    return sorted(out)


# -------------------------------------------------------- C: authority delta
def authority_delta():
    """Level-A pairs CPIC carries that this build does not.

    Two kinds, and the second is the dangerous one. A pair we do not carry at all
    is a known limit — the build says «not covered» and a person can act on that.
    A drug we DO carry while modelling fewer genes than CPIC names for it answers
    confidently from an incomplete model, which is what happened with TPMT alone.
    """
    kb = _load("cpic_drug_gene.json")
    pairs = _load("cpic_pairs.json")["pairs"]
    ours = {}
    for drug in kb.get("drugs", []):
        genes = {drug.get("gene")} | set(drug.get("also_genes") or [])
        for n in drug.get("names", []):
            ours[n.lower()] = ours.get(n.lower(), set()) | genes
    by_drug = {}
    for p in pairs:
        by_drug.setdefault(p["drug"].lower(), set()).add(p["gene"])

    partial, absent = [], []
    for drug, cpic_genes in sorted(by_drug.items()):
        mine = ours.get(drug)
        if mine is None:
            absent.append(f"{drug}: {'/'.join(sorted(cpic_genes))}")
        else:
            missing = cpic_genes - mine
            if missing:
                partial.append(f"{drug}: carried with {'/'.join(sorted(mine))}, "
                               f"CPIC also names {'/'.join(sorted(missing))}")
    return {"partial": sorted(partial), "absent": sorted(absent),
            "carried": len(by_drug) - len(absent), "total": len(by_drug)}


def unexplained_flags():
    """A marker that can be FLAGGED and has nothing to say about the flag.

    The pharmacogenetic case was a phenotype the model could emit with no row to
    answer it. The laboratory tree has the same shape: 312 markers carry
    reference bounds, so each can print «high» or «low» next to a person's own
    number — and if no catalogue explains what the deviation means or what to do,
    the report is a red flag with no sentence, which is the medical version of
    «no recommendation in the catalogue».
    """
    markers = _load("lab_markers.json").get("markers", {})
    thresholds = _load("clinical_thresholds.json").get("markers", {})
    ruled = set()
    for rule in _load("test_rules.json").get("rules", []):
        for key in ("marker", "markers", "if_marker", "prerequisites", "then_tests"):
            v = rule.get(key)
            if isinstance(v, str):
                ruled.add(v)
            elif isinstance(v, list):
                ruled.update(x for x in v if isinstance(x, str))
    out = []
    for name, m in sorted(markers.items()):
        can_flag = any(m.get(k) is not None for k in
                       ("ref_low", "ref_high", "target_low", "target_high"))
        if not can_flag:
            continue
        explained = (name in thresholds or name in ruled
                     or any(m.get(k) for k in ("note", "why", "meaning", "interpretation")))
        if not explained:
            out.append(name)
    return out


def unmapped_identifiers():
    """A marker with no LOINC code.

    The base states that it maps its markers to LOINC. The statement is true of
    the ones that carry a code and silent about the rest, and silence reads as
    coverage. Counted here so the claim is a fraction.
    """
    markers = _load("lab_markers.json").get("markers", {})
    tests = _load("lab_test_meta.json").get("tests", {})
    return sorted(n for n in markers if not (tests.get(n) or {}).get("loinc"))


def markers_without_an_english_name():
    """A marker the dictionary can only recognise in Russian.

    The catalogue carries Russian names for every marker and English names for
    part of them, and a marker with no English name is invisible on an English
    form: `ingest-labs` on a US export or a PGP phenotype table walks past it in
    silence, exactly as it walked past a rheumatoid factor that was printed,
    dated and unambiguous. This is not a bug in one entry — it is a measurable
    fraction, and it belongs next to the other gaps rather than being repaired
    one row at a time whenever somebody trips over a row.
    """
    markers = _load("lab_markers.json").get("markers", {})
    out = []
    for key, spec in markers.items():
        names = (((spec.get("labels") or {}).get("en") or {}).get("names") or [])
        if not names:
            out.append(key)
    return sorted(out)


def ingest_artefacts_without_a_reader():
    """A file `src/ingest/` writes into the profile that no core module reads.

    The audit's single structural finding: `src/ingest/` and `src/scholion/` are
    joined by the filesystem and by convention, and the convention was checked
    nowhere. Four separate defects came out of it — an ancestry verdict, star
    alleles for eighteen genes, callability, and confidence modifiers, each
    computed, written and read by no one. This enumerator is the check the audit
    asked for, and it is mechanical: the writers name their own outputs.

    An artefact is «read» when its file name occurs anywhere in `src/scholion/`.
    A name is a weak link — it can be built from pieces — but it is the same link
    the pipeline itself relies on, and if the core cannot even mention the file,
    it certainly does not read it.
    """
    ingest = SRC / "ingest"
    if not ingest.is_dir():
        return []
    core_text = "\n".join(p.read_text(encoding="utf-8", errors="ignore")
                          for p in (SRC / "scholion").rglob("*.py"))
    written = {}
    pattern = re.compile(r"""profile[/'"\s]{1,3}([A-Za-z0-9_]+\.(?:tsv|json|csv|bed))""")
    for f in sorted(ingest.rglob("*")):
        if not f.is_file() or f.suffix not in (".py", ".sh"):
            continue
        for name in pattern.findall(f.read_text(encoding="utf-8", errors="ignore")):
            written.setdefault(name, set()).add(f.name)
    return sorted(f"{name} ← {', '.join(sorted(src))}"
                  for name, src in written.items() if name not in core_text)


def collect():
    delta = authority_delta()
    return {"orphan_facts": orphan_facts(),
            "unexplained_flags": unexplained_flags(),
            "unmapped_identifiers": unmapped_identifiers(),
            "markers_without_an_english_name": markers_without_an_english_name(),
            "ingest_artefacts_without_a_reader": ingest_artefacts_without_a_reader(),
            "coverage_holes": coverage_holes(),
            "authority_partial": delta["partial"],
            "authority_absent": delta["absent"],
            "_carried": delta["carried"], "_total": delta["total"]}


def main(argv):
    now = collect()
    strict = "--strict" in argv
    accept = "--accept" in argv

    if accept:
        BASELINE.write_text(json.dumps(now, ensure_ascii=False, indent=2) + "\n",
                            encoding="utf-8")
        print(f"✅ baseline accepted: {BASELINE.relative_to(ROOT)}")
        return 0

    try:
        base = json.loads(BASELINE.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        base = {}

    print(f"CPIC level-A drugs carried: {now['_carried']}/{now['_total']}"
          f" — the rest are enumerated below, not implied.\n")
    grew = []
    for key, title in (("authority_partial", "Carried with FEWER genes than CPIC names "
                                             "(answers confidently from an incomplete model)"),
                       ("coverage_holes", "A phenotype the model can produce with no guidance row"),
                       ("orphan_facts", "Written by the pipeline, read by nothing"),
                       ("unexplained_flags", "Can print a flag on a person's number with "
                                             "nothing that explains it"),
                       ("unmapped_identifiers", "Laboratory markers with no LOINC code"),
                       ("authority_absent", "Level-A pairs not carried at all (a stated limit)")):
        items = now.get(key, [])
        was = set(base.get(key, []))
        new = [i for i in items if i not in was]
        print(f"{title} — {len(items)}" + (f", NEW: {len(new)}" if new else ""))
        for i in items[:12]:
            print(("  ! " if i in new else "  · ") + i)
        if len(items) > 12:
            print(f"  … and {len(items) - 12} more")
        print()
        grew += [f"{key}: {i}" for i in new]

    if grew:
        print("A gap that did not exist before has appeared:")
        for g in grew[:20]:
            print("  ✗ " + g)
        print("\nFix it, or accept it deliberately with --accept so the new gap is "
              "recorded and visible in review.")
        return 1 if strict else 0
    print("✅ no new gaps against the baseline")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
